pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot/Renovate/Requires.io pull requests
    conditions:
      - or:
          - and:
              - author=dependabot[bot]
          - and:
              - title~=^\[requires.io\]
              - head~=^requires-io
          - and:
              - author=renovate[bot]
      - check-success~=^deploy
    actions:
      merge:
        method: merge
