name: pake homepage

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        node: ["16"]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 7
      - name: setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: install others lib (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt install libdbus-1-dev \
            libsoup2.4-dev \
            libjavascriptcoregtk-4.0-dev \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            gnome-video-effects \
            gnome-video-effects-extra
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/:$PKG_CONFIG_PATH
      - name: install pake-cli
        run: pnpm install -g pake-cli
      - name: pake url
        run: pake https://augusmeow.github.io/ --name Augus
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.platform }}.zip
          path: |
            *.dmg
            *.deb
            *.msi
          retention-days: 3
